[server]
address = "localhost" # domain or ip
port = 30543

[ratelimiter.unary]
limit = 5
interval = 1 # secs

[ratelimiter.stream]
limit = 100
interval = 1 # secs

[services.files]
enabled = false

[services.music]
enabled = false

[services.images]
enabled = false

[services.llm]
enabled = false
