[server]
address = "localhost" # domain or ip
port = 30543

[ratelimiter]
enabled = false
limit = 50
interval = 1 # secs

[services.files]
enabled = false

[services.music]
enabled = false

[services.images]
enabled = false

[services.llm]
enabled = false
