// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: data/data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_InitFile_FullMethodName              = "/data.DataService/InitFile"
	DataService_SaveFile_FullMethodName              = "/data.DataService/SaveFile"
	DataService_ReadFile_FullMethodName              = "/data.DataService/ReadFile"
	DataService_GetSum_FullMethodName                = "/data.DataService/GetSum"
	DataService_GetFiles_FullMethodName              = "/data.DataService/GetFiles"
	DataService_GetAvailableDiskSpace_FullMethodName = "/data.DataService/GetAvailableDiskSpace"
	DataService_CreateDir_FullMethodName             = "/data.DataService/CreateDir"
	DataService_RemoveDir_FullMethodName             = "/data.DataService/RemoveDir"
	DataService_RemoveFile_FullMethodName            = "/data.DataService/RemoveFile"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	InitFile(ctx context.Context, in *RequiredFile, opts ...grpc.CallOption) (*InitInfo, error)
	SaveFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SaveFileChunk, emptypb.Empty], error)
	ReadFile(ctx context.Context, in *FileID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	GetSum(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*SHASum, error)
	GetFiles(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*FilesList, error)
	GetAvailableDiskSpace(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*Size, error)
	CreateDir(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveDir(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveFile(ctx context.Context, in *RequiredFile, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) InitFile(ctx context.Context, in *RequiredFile, opts ...grpc.CallOption) (*InitInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitInfo)
	err := c.cc.Invoke(ctx, DataService_InitFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) SaveFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SaveFileChunk, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_SaveFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SaveFileChunk, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_SaveFileClient = grpc.ClientStreamingClient[SaveFileChunk, emptypb.Empty]

func (c *dataServiceClient) ReadFile(ctx context.Context, in *FileID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], DataService_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileID, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ReadFileClient = grpc.ServerStreamingClient[Chunk]

func (c *dataServiceClient) GetSum(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*SHASum, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SHASum)
	err := c.cc.Invoke(ctx, DataService_GetSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetFiles(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*FilesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilesList)
	err := c.cc.Invoke(ctx, DataService_GetFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetAvailableDiskSpace(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*Size, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Size)
	err := c.cc.Invoke(ctx, DataService_GetAvailableDiskSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) CreateDir(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataService_CreateDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) RemoveDir(ctx context.Context, in *Directory, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataService_RemoveDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) RemoveFile(ctx context.Context, in *RequiredFile, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DataService_RemoveFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	InitFile(context.Context, *RequiredFile) (*InitInfo, error)
	SaveFile(grpc.ClientStreamingServer[SaveFileChunk, emptypb.Empty]) error
	ReadFile(*FileID, grpc.ServerStreamingServer[Chunk]) error
	GetSum(context.Context, *FileID) (*SHASum, error)
	GetFiles(context.Context, *Directory) (*FilesList, error)
	GetAvailableDiskSpace(context.Context, *Directory) (*Size, error)
	CreateDir(context.Context, *Directory) (*emptypb.Empty, error)
	RemoveDir(context.Context, *Directory) (*emptypb.Empty, error)
	RemoveFile(context.Context, *RequiredFile) (*emptypb.Empty, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) InitFile(context.Context, *RequiredFile) (*InitInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitFile not implemented")
}
func (UnimplementedDataServiceServer) SaveFile(grpc.ClientStreamingServer[SaveFileChunk, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SaveFile not implemented")
}
func (UnimplementedDataServiceServer) ReadFile(*FileID, grpc.ServerStreamingServer[Chunk]) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedDataServiceServer) GetSum(context.Context, *FileID) (*SHASum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSum not implemented")
}
func (UnimplementedDataServiceServer) GetFiles(context.Context, *Directory) (*FilesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedDataServiceServer) GetAvailableDiskSpace(context.Context, *Directory) (*Size, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableDiskSpace not implemented")
}
func (UnimplementedDataServiceServer) CreateDir(context.Context, *Directory) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDir not implemented")
}
func (UnimplementedDataServiceServer) RemoveDir(context.Context, *Directory) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDir not implemented")
}
func (UnimplementedDataServiceServer) RemoveFile(context.Context, *RequiredFile) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFile not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_InitFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequiredFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).InitFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_InitFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).InitFile(ctx, req.(*RequiredFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_SaveFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).SaveFile(&grpc.GenericServerStream[SaveFileChunk, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_SaveFileServer = grpc.ClientStreamingServer[SaveFileChunk, emptypb.Empty]

func _DataService_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).ReadFile(m, &grpc.GenericServerStream[FileID, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ReadFileServer = grpc.ServerStreamingServer[Chunk]

func _DataService_GetSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetSum(ctx, req.(*FileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetFiles(ctx, req.(*Directory))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetAvailableDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetAvailableDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetAvailableDiskSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetAvailableDiskSpace(ctx, req.(*Directory))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_CreateDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).CreateDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_CreateDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).CreateDir(ctx, req.(*Directory))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_RemoveDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Directory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).RemoveDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_RemoveDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).RemoveDir(ctx, req.(*Directory))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_RemoveFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequiredFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).RemoveFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_RemoveFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).RemoveFile(ctx, req.(*RequiredFile))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitFile",
			Handler:    _DataService_InitFile_Handler,
		},
		{
			MethodName: "GetSum",
			Handler:    _DataService_GetSum_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _DataService_GetFiles_Handler,
		},
		{
			MethodName: "GetAvailableDiskSpace",
			Handler:    _DataService_GetAvailableDiskSpace_Handler,
		},
		{
			MethodName: "CreateDir",
			Handler:    _DataService_CreateDir_Handler,
		},
		{
			MethodName: "RemoveDir",
			Handler:    _DataService_RemoveDir_Handler,
		},
		{
			MethodName: "RemoveFile",
			Handler:    _DataService_RemoveFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveFile",
			Handler:       _DataService_SaveFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadFile",
			Handler:       _DataService_ReadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data/data.proto",
}
