syntax = "proto3";
package data;
option go_package = "github.com/braginantonev/mhserver/proto/data";

import "google/protobuf/empty.proto";

service DataService {
    rpc InitFile (RequiredFile) returns (FileID);
    rpc SaveFile (stream SaveFileChunk) returns (google.protobuf.Empty);
    rpc ReadFile (FileID) returns (stream Chunk);
    rpc GetFileChunk (GetChunk) returns (Chunk);
    rpc GetSum (FileID) returns (SHASum);
    rpc GetFiles (Directory) returns (FilesList);
	rpc GetAvailableDiskSpace (Directory) returns (Size);
	rpc CreateDir (Directory) returns (google.protobuf.Empty);
	rpc RemoveDir (Directory) returns (google.protobuf.Empty);
    rpc RemoveFile (RequiredFile) returns (google.protobuf.Empty);
}

message Directory {
    string user = 1;
    string value = 2;
}

message RequiredFile {
    Directory dir = 1;
    string name = 2;
}

message FileID {
    string value = 1;
}

message Chunk {
    bytes data = 1;
    uint64 offset = 2;
}

message SaveFileChunk {
    FileID id = 1;
    Chunk value = 2;
}

message GetChunk {
    FileID id = 1;
    uint64 size = 2;
    uint64 offset = 3;
}

message SHASum {
    bytes value = 1;
}

message FileInfo {
    string name = 1;
    bool isDir = 2;
    uint64 size = 3;
    uint64 modTime = 4;
}

message FilesList {
    repeated FileInfo value = 1;
}

message Size {
    uint64 value = 1;
}
