// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_File  DataType = 0
	DataType_Image DataType = 1
	DataType_Music DataType = 2 //Todo
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "File",
		1: "Image",
		2: "Music",
	}
	DataType_value = map[string]int32{
		"File":  0,
		"Image": 1,
		"Music": 2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_data_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_data_data_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_Create Action = 0
	Action_Patch  Action = 1
	Action_Finish Action = 2
	Action_Delete Action = 3
	Action_Get    Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "Create",
		1: "Patch",
		2: "Finish",
		3: "Delete",
		4: "Get",
	}
	Action_value = map[string]int32{
		"Create": 0,
		"Patch":  1,
		"Finish": 2,
		"Delete": 3,
		"Get":    4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_data_data_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_data_data_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

type FilePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=isLast,proto3" json:"isLast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *FilePart) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FilePart) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FilePart) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type DataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=data.DataType" json:"type,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataInfo) Reset() {
	*x = DataInfo{}
	mi := &file_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataInfo) ProtoMessage() {}

func (x *DataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataInfo.ProtoReflect.Descriptor instead.
func (*DataInfo) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataInfo) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_File
}

func (x *DataInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DataInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *DataInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Action        Action                 `protobuf:"varint,2,opt,name=action,proto3,enum=data.Action" json:"action,omitempty"`
	Part          *FilePart              `protobuf:"bytes,3,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetInfo() *DataInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Data) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_Create
}

func (x *Data) GetPart() *FilePart {
	if x != nil {
		return x.Part
	}
	return nil
}

var File_data_data_proto protoreflect.FileDescriptor

const file_data_data_proto_rawDesc = "" +
	"\n" +
	"\x0fdata/data.proto\x12\x04data\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\bFilePart\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06isLast\x18\x03 \x01(\bR\x06isLast\"V\n" +
	"\bDataInfo\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.data.DataTypeR\x04type\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\"t\n" +
	"\x04Data\x12\"\n" +
	"\x04info\x18\x01 \x01(\v2\x0e.data.DataInfoR\x04info\x12$\n" +
	"\x06action\x18\x02 \x01(\x0e2\f.data.ActionR\x06action\x12\"\n" +
	"\x04part\x18\x03 \x01(\v2\x0e.data.FilePartR\x04part**\n" +
	"\bDataType\x12\b\n" +
	"\x04File\x10\x00\x12\t\n" +
	"\x05Image\x10\x01\x12\t\n" +
	"\x05Music\x10\x02*@\n" +
	"\x06Action\x12\n" +
	"\n" +
	"\x06Create\x10\x00\x12\t\n" +
	"\x05Patch\x10\x01\x12\n" +
	"\n" +
	"\x06Finish\x10\x02\x12\n" +
	"\n" +
	"\x06Delete\x10\x03\x12\a\n" +
	"\x03Get\x10\x042d\n" +
	"\vDataService\x12.\n" +
	"\bSaveData\x12\n" +
	".data.Data\x1a\x16.google.protobuf.Empty\x12%\n" +
	"\aGetData\x12\n" +
	".data.Data\x1a\x0e.data.FilePartB.Z,github.com/braginantonev/mhserver/proto/datab\x06proto3"

var (
	file_data_data_proto_rawDescOnce sync.Once
	file_data_data_proto_rawDescData []byte
)

func file_data_data_proto_rawDescGZIP() []byte {
	file_data_data_proto_rawDescOnce.Do(func() {
		file_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)))
	})
	return file_data_data_proto_rawDescData
}

var file_data_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_data_proto_goTypes = []any{
	(DataType)(0),         // 0: data.DataType
	(Action)(0),           // 1: data.Action
	(*FilePart)(nil),      // 2: data.FilePart
	(*DataInfo)(nil),      // 3: data.DataInfo
	(*Data)(nil),          // 4: data.Data
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_data_data_proto_depIdxs = []int32{
	0, // 0: data.DataInfo.type:type_name -> data.DataType
	3, // 1: data.Data.info:type_name -> data.DataInfo
	1, // 2: data.Data.action:type_name -> data.Action
	2, // 3: data.Data.part:type_name -> data.FilePart
	4, // 4: data.DataService.SaveData:input_type -> data.Data
	4, // 5: data.DataService.GetData:input_type -> data.Data
	5, // 6: data.DataService.SaveData:output_type -> google.protobuf.Empty
	2, // 7: data.DataService.GetData:output_type -> data.FilePart
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_data_proto_init() }
func file_data_data_proto_init() {
	if File_data_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_data_proto_goTypes,
		DependencyIndexes: file_data_data_proto_depIdxs,
		EnumInfos:         file_data_data_proto_enumTypes,
		MessageInfos:      file_data_data_proto_msgTypes,
	}.Build()
	File_data_data_proto = out.File
	file_data_data_proto_goTypes = nil
	file_data_data_proto_depIdxs = nil
}
