// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_File  FileType = 0
	FileType_Image FileType = 1
	FileType_Music FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "File",
		1: "Image",
		2: "Music",
	}
	FileType_value = map[string]int32{
		"File":  0,
		"Image": 1,
		"Music": 2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_data_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_data_data_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

type ConnectionMode int32

const (
	ConnectionMode_R  ConnectionMode = 0
	ConnectionMode_RW ConnectionMode = 1
)

// Enum value maps for ConnectionMode.
var (
	ConnectionMode_name = map[int32]string{
		0: "R",
		1: "RW",
	}
	ConnectionMode_value = map[string]int32{
		"R":  0,
		"RW": 1,
	}
)

func (x ConnectionMode) Enum() *ConnectionMode {
	p := new(ConnectionMode)
	*p = x
	return p
}

func (x ConnectionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_data_data_proto_enumTypes[1].Descriptor()
}

func (ConnectionMode) Type() protoreflect.EnumType {
	return &file_data_data_proto_enumTypes[1]
}

func (x ConnectionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionMode.Descriptor instead.
func (ConnectionMode) EnumDescriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

type FilePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *FilePart) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *FilePart) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Mode          ConnectionMode         `protobuf:"varint,2,opt,name=mode,proto3,enum=data.ConnectionMode" json:"mode,omitempty"`
	Directory     string                 `protobuf:"bytes,3,opt,name=directory,proto3" json:"directory,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	Filetype      FileType               `protobuf:"varint,5,opt,name=filetype,proto3,enum=data.FileType" json:"filetype,omitempty"`
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionRequest) GetMode() ConnectionMode {
	if x != nil {
		return x.Mode
	}
	return ConnectionMode_R
}

func (x *ConnectionRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *ConnectionRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ConnectionRequest) GetFiletype() FileType {
	if x != nil {
		return x.Filetype
	}
	return FileType_File
}

func (x *ConnectionRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SaveChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Data          *FilePart              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveChunk) Reset() {
	*x = SaveChunk{}
	mi := &file_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChunk) ProtoMessage() {}

func (x *SaveChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChunk.ProtoReflect.Descriptor instead.
func (*SaveChunk) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *SaveChunk) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *SaveChunk) GetData() *FilePart {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	ChunkId       int32                  `protobuf:"varint,2,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunk) Reset() {
	*x = GetChunk{}
	mi := &file_data_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunk) ProtoMessage() {}

func (x *GetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunk.ProtoReflect.Descriptor instead.
func (*GetChunk) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunk) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetChunk) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_data_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{4}
}

func (x *Directory) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Directory) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	ChunkSize     uint64                 `protobuf:"varint,2,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	ChunksCount   int32                  `protobuf:"varint,3,opt,name=chunksCount,proto3" json:"chunksCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_data_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{5}
}

func (x *Connection) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Connection) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Connection) GetChunksCount() int32 {
	if x != nil {
		return x.ChunksCount
	}
	return 0
}

type SHASum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHASum) Reset() {
	*x = SHASum{}
	mi := &file_data_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHASum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHASum) ProtoMessage() {}

func (x *SHASum) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHASum.ProtoReflect.Descriptor instead.
func (*SHASum) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{6}
}

func (x *SHASum) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=modTime,proto3" json:"modTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_data_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type FilesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*FileInfo            `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesList) Reset() {
	*x = FilesList{}
	mi := &file_data_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesList) ProtoMessage() {}

func (x *FilesList) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesList.ProtoReflect.Descriptor instead.
func (*FilesList) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{8}
}

func (x *FilesList) GetValue() []*FileInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_data_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{9}
}

func (x *Size) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_data_data_proto protoreflect.FileDescriptor

const file_data_data_proto_rawDesc = "" +
	"\n" +
	"\x0fdata/data.proto\x12\x04data\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\bFilePart\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\xd3\x01\n" +
	"\x11ConnectionRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12(\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x14.data.ConnectionModeR\x04mode\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\tR\tdirectory\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12*\n" +
	"\bfiletype\x18\x05 \x01(\x0e2\x0e.data.FileTypeR\bfiletype\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\"C\n" +
	"\tSaveChunk\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\"\n" +
	"\x04data\x18\x02 \x01(\v2\x0e.data.FilePartR\x04data\"8\n" +
	"\bGetChunk\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x18\n" +
	"\achunkId\x18\x02 \x01(\x05R\achunkId\"5\n" +
	"\tDirectory\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"`\n" +
	"\n" +
	"Connection\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x1c\n" +
	"\tchunkSize\x18\x02 \x01(\x04R\tchunkSize\x12 \n" +
	"\vchunksCount\x18\x03 \x01(\x05R\vchunksCount\"\x1e\n" +
	"\x06SHASum\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"b\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05isDir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x18\n" +
	"\amodTime\x18\x04 \x01(\x03R\amodTime\"1\n" +
	"\tFilesList\x12$\n" +
	"\x05value\x18\x01 \x03(\v2\x0e.data.FileInfoR\x05value\"\x1c\n" +
	"\x04Size\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value**\n" +
	"\bFileType\x12\b\n" +
	"\x04File\x10\x00\x12\t\n" +
	"\x05Image\x10\x01\x12\t\n" +
	"\x05Music\x10\x02*\x1f\n" +
	"\x0eConnectionMode\x12\x05\n" +
	"\x01R\x10\x00\x12\x06\n" +
	"\x02RW\x10\x012\xa4\x03\n" +
	"\vDataService\x12=\n" +
	"\x10CreateConnection\x12\x17.data.ConnectionRequest\x1a\x10.data.Connection\x123\n" +
	"\bSaveData\x12\x0f.data.SaveChunk\x1a\x16.google.protobuf.Empty\x12)\n" +
	"\aGetData\x12\x0e.data.GetChunk\x1a\x0e.data.FilePart\x12&\n" +
	"\x06GetSum\x12\x0e.data.GetChunk\x1a\f.data.SHASum\x12,\n" +
	"\bGetFiles\x12\x0f.data.Directory\x1a\x0f.data.FilesList\x124\n" +
	"\x15GetAvailableDiskSpace\x12\x0f.data.Directory\x1a\n" +
	".data.Size\x124\n" +
	"\tCreateDir\x12\x0f.data.Directory\x1a\x16.google.protobuf.Empty\x124\n" +
	"\tRemoveDir\x12\x0f.data.Directory\x1a\x16.google.protobuf.EmptyB.Z,github.com/braginantonev/mhserver/proto/datab\x06proto3"

var (
	file_data_data_proto_rawDescOnce sync.Once
	file_data_data_proto_rawDescData []byte
)

func file_data_data_proto_rawDescGZIP() []byte {
	file_data_data_proto_rawDescOnce.Do(func() {
		file_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)))
	})
	return file_data_data_proto_rawDescData
}

var file_data_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_data_data_proto_goTypes = []any{
	(FileType)(0),             // 0: data.FileType
	(ConnectionMode)(0),       // 1: data.ConnectionMode
	(*FilePart)(nil),          // 2: data.FilePart
	(*ConnectionRequest)(nil), // 3: data.ConnectionRequest
	(*SaveChunk)(nil),         // 4: data.SaveChunk
	(*GetChunk)(nil),          // 5: data.GetChunk
	(*Directory)(nil),         // 6: data.Directory
	(*Connection)(nil),        // 7: data.Connection
	(*SHASum)(nil),            // 8: data.SHASum
	(*FileInfo)(nil),          // 9: data.FileInfo
	(*FilesList)(nil),         // 10: data.FilesList
	(*Size)(nil),              // 11: data.Size
	(*emptypb.Empty)(nil),     // 12: google.protobuf.Empty
}
var file_data_data_proto_depIdxs = []int32{
	1,  // 0: data.ConnectionRequest.mode:type_name -> data.ConnectionMode
	0,  // 1: data.ConnectionRequest.filetype:type_name -> data.FileType
	2,  // 2: data.SaveChunk.data:type_name -> data.FilePart
	9,  // 3: data.FilesList.value:type_name -> data.FileInfo
	3,  // 4: data.DataService.CreateConnection:input_type -> data.ConnectionRequest
	4,  // 5: data.DataService.SaveData:input_type -> data.SaveChunk
	5,  // 6: data.DataService.GetData:input_type -> data.GetChunk
	5,  // 7: data.DataService.GetSum:input_type -> data.GetChunk
	6,  // 8: data.DataService.GetFiles:input_type -> data.Directory
	6,  // 9: data.DataService.GetAvailableDiskSpace:input_type -> data.Directory
	6,  // 10: data.DataService.CreateDir:input_type -> data.Directory
	6,  // 11: data.DataService.RemoveDir:input_type -> data.Directory
	7,  // 12: data.DataService.CreateConnection:output_type -> data.Connection
	12, // 13: data.DataService.SaveData:output_type -> google.protobuf.Empty
	2,  // 14: data.DataService.GetData:output_type -> data.FilePart
	8,  // 15: data.DataService.GetSum:output_type -> data.SHASum
	10, // 16: data.DataService.GetFiles:output_type -> data.FilesList
	11, // 17: data.DataService.GetAvailableDiskSpace:output_type -> data.Size
	12, // 18: data.DataService.CreateDir:output_type -> google.protobuf.Empty
	12, // 19: data.DataService.RemoveDir:output_type -> google.protobuf.Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_data_data_proto_init() }
func file_data_data_proto_init() {
	if File_data_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_data_proto_goTypes,
		DependencyIndexes: file_data_data_proto_depIdxs,
		EnumInfos:         file_data_data_proto_enumTypes,
		MessageInfos:      file_data_data_proto_msgTypes,
	}.Build()
	File_data_data_proto = out.File
	file_data_data_proto_goTypes = nil
	file_data_data_proto_depIdxs = nil
}
