// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *Directory) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Directory) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RequiredFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           *Directory             `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NewSize       *uint64                `protobuf:"varint,3,opt,name=newSize,proto3,oneof" json:"newSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredFile) Reset() {
	*x = RequiredFile{}
	mi := &file_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredFile) ProtoMessage() {}

func (x *RequiredFile) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredFile.ProtoReflect.Descriptor instead.
func (*RequiredFile) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *RequiredFile) GetDir() *Directory {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *RequiredFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequiredFile) GetNewSize() uint64 {
	if x != nil && x.NewSize != nil {
		return *x.NewSize
	}
	return 0
}

type FileID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileID) Reset() {
	*x = FileID{}
	mi := &file_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileID) ProtoMessage() {}

func (x *FileID) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileID.ProtoReflect.Descriptor instead.
func (*FileID) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *FileID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type InitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileID        *FileID                `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	MaxChunkSize  uint64                 `protobuf:"varint,2,opt,name=maxChunkSize,proto3" json:"maxChunkSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitInfo) Reset() {
	*x = InitInfo{}
	mi := &file_data_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitInfo) ProtoMessage() {}

func (x *InitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitInfo.ProtoReflect.Descriptor instead.
func (*InitInfo) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{3}
}

func (x *InitInfo) GetFileID() *FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

func (x *InitInfo) GetMaxChunkSize() uint64 {
	if x != nil {
		return x.MaxChunkSize
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_data_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{4}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SaveFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *FileID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         *Chunk                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveFileChunk) Reset() {
	*x = SaveFileChunk{}
	mi := &file_data_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveFileChunk) ProtoMessage() {}

func (x *SaveFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveFileChunk.ProtoReflect.Descriptor instead.
func (*SaveFileChunk) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{5}
}

func (x *SaveFileChunk) GetId() *FileID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SaveFileChunk) GetValue() *Chunk {
	if x != nil {
		return x.Value
	}
	return nil
}

type SHASum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHASum) Reset() {
	*x = SHASum{}
	mi := &file_data_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHASum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHASum) ProtoMessage() {}

func (x *SHASum) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHASum.ProtoReflect.Descriptor instead.
func (*SHASum) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{6}
}

func (x *SHASum) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       uint64                 `protobuf:"varint,4,opt,name=modTime,proto3" json:"modTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_data_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{7}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTime() uint64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type FilesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*FileInfo            `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesList) Reset() {
	*x = FilesList{}
	mi := &file_data_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesList) ProtoMessage() {}

func (x *FilesList) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesList.ProtoReflect.Descriptor instead.
func (*FilesList) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{8}
}

func (x *FilesList) GetValue() []*FileInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint64                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_data_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{9}
}

func (x *Size) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_data_data_proto protoreflect.FileDescriptor

const file_data_data_proto_rawDesc = "" +
	"\n" +
	"\x0fdata/data.proto\x12\x04data\x1a\x1bgoogle/protobuf/empty.proto\"5\n" +
	"\tDirectory\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"p\n" +
	"\fRequiredFile\x12!\n" +
	"\x03dir\x18\x01 \x01(\v2\x0f.data.DirectoryR\x03dir\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\anewSize\x18\x03 \x01(\x04H\x00R\anewSize\x88\x01\x01B\n" +
	"\n" +
	"\b_newSize\"\x1e\n" +
	"\x06FileID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"T\n" +
	"\bInitInfo\x12$\n" +
	"\x06fileID\x18\x01 \x01(\v2\f.data.FileIDR\x06fileID\x12\"\n" +
	"\fmaxChunkSize\x18\x02 \x01(\x04R\fmaxChunkSize\"3\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"P\n" +
	"\rSaveFileChunk\x12\x1c\n" +
	"\x02id\x18\x01 \x01(\v2\f.data.FileIDR\x02id\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.data.ChunkR\x05value\"\x1e\n" +
	"\x06SHASum\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"b\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05isDir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x18\n" +
	"\amodTime\x18\x04 \x01(\x04R\amodTime\"1\n" +
	"\tFilesList\x12$\n" +
	"\x05value\x18\x01 \x03(\v2\x0e.data.FileInfoR\x05value\"\x1c\n" +
	"\x04Size\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value2\xd1\x03\n" +
	"\vDataService\x12.\n" +
	"\bInitFile\x12\x12.data.RequiredFile\x1a\x0e.data.InitInfo\x129\n" +
	"\bSaveFile\x12\x13.data.SaveFileChunk\x1a\x16.google.protobuf.Empty(\x01\x12'\n" +
	"\bReadFile\x12\f.data.FileID\x1a\v.data.Chunk0\x01\x12$\n" +
	"\x06GetSum\x12\f.data.FileID\x1a\f.data.SHASum\x12,\n" +
	"\bGetFiles\x12\x0f.data.Directory\x1a\x0f.data.FilesList\x124\n" +
	"\x15GetAvailableDiskSpace\x12\x0f.data.Directory\x1a\n" +
	".data.Size\x124\n" +
	"\tCreateDir\x12\x0f.data.Directory\x1a\x16.google.protobuf.Empty\x124\n" +
	"\tRemoveDir\x12\x0f.data.Directory\x1a\x16.google.protobuf.Empty\x128\n" +
	"\n" +
	"RemoveFile\x12\x12.data.RequiredFile\x1a\x16.google.protobuf.EmptyB.Z,github.com/braginantonev/mhserver/proto/datab\x06proto3"

var (
	file_data_data_proto_rawDescOnce sync.Once
	file_data_data_proto_rawDescData []byte
)

func file_data_data_proto_rawDescGZIP() []byte {
	file_data_data_proto_rawDescOnce.Do(func() {
		file_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)))
	})
	return file_data_data_proto_rawDescData
}

var file_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_data_data_proto_goTypes = []any{
	(*Directory)(nil),     // 0: data.Directory
	(*RequiredFile)(nil),  // 1: data.RequiredFile
	(*FileID)(nil),        // 2: data.FileID
	(*InitInfo)(nil),      // 3: data.InitInfo
	(*Chunk)(nil),         // 4: data.Chunk
	(*SaveFileChunk)(nil), // 5: data.SaveFileChunk
	(*SHASum)(nil),        // 6: data.SHASum
	(*FileInfo)(nil),      // 7: data.FileInfo
	(*FilesList)(nil),     // 8: data.FilesList
	(*Size)(nil),          // 9: data.Size
	(*emptypb.Empty)(nil), // 10: google.protobuf.Empty
}
var file_data_data_proto_depIdxs = []int32{
	0,  // 0: data.RequiredFile.dir:type_name -> data.Directory
	2,  // 1: data.InitInfo.fileID:type_name -> data.FileID
	2,  // 2: data.SaveFileChunk.id:type_name -> data.FileID
	4,  // 3: data.SaveFileChunk.value:type_name -> data.Chunk
	7,  // 4: data.FilesList.value:type_name -> data.FileInfo
	1,  // 5: data.DataService.InitFile:input_type -> data.RequiredFile
	5,  // 6: data.DataService.SaveFile:input_type -> data.SaveFileChunk
	2,  // 7: data.DataService.ReadFile:input_type -> data.FileID
	2,  // 8: data.DataService.GetSum:input_type -> data.FileID
	0,  // 9: data.DataService.GetFiles:input_type -> data.Directory
	0,  // 10: data.DataService.GetAvailableDiskSpace:input_type -> data.Directory
	0,  // 11: data.DataService.CreateDir:input_type -> data.Directory
	0,  // 12: data.DataService.RemoveDir:input_type -> data.Directory
	1,  // 13: data.DataService.RemoveFile:input_type -> data.RequiredFile
	3,  // 14: data.DataService.InitFile:output_type -> data.InitInfo
	10, // 15: data.DataService.SaveFile:output_type -> google.protobuf.Empty
	4,  // 16: data.DataService.ReadFile:output_type -> data.Chunk
	6,  // 17: data.DataService.GetSum:output_type -> data.SHASum
	8,  // 18: data.DataService.GetFiles:output_type -> data.FilesList
	9,  // 19: data.DataService.GetAvailableDiskSpace:output_type -> data.Size
	10, // 20: data.DataService.CreateDir:output_type -> google.protobuf.Empty
	10, // 21: data.DataService.RemoveDir:output_type -> google.protobuf.Empty
	10, // 22: data.DataService.RemoveFile:output_type -> google.protobuf.Empty
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_data_data_proto_init() }
func file_data_data_proto_init() {
	if File_data_data_proto != nil {
		return
	}
	file_data_data_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_data_proto_goTypes,
		DependencyIndexes: file_data_data_proto_depIdxs,
		MessageInfos:      file_data_data_proto_msgTypes,
	}.Build()
	File_data_data_proto = out.File
	file_data_data_proto_goTypes = nil
	file_data_data_proto_depIdxs = nil
}
